version: "3"
services:
  express-server:
    build: ./server
    image: ${DOCKERHUB_NAME}/${IMAGE_NAME}/${IMAGE_VERSION}
    env_file: .env

  frontend:
    build: ./frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    links:
      - express-server
    command: ["npm", "start"]


volumes:
  node-modules: